# .github/workflows/douban.yml
name: douban
on: 
  workflow_dispatch:
  schedule:
  - cron: "0 0,0,12,23 * * *"
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: delete old file
      run: |
        rm -rf ./*
    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 266851825
        type: movie
        format: csv
        dir: ./
  
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "update douban" -a
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
